// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDStzj4GMSxJxWr8yt1PwlQ6tmrjWPSU_I',
    appId: '1:550489230441:web:8cdddf77aa5558a34626f8',
    messagingSenderId: '550489230441',
    projectId: 'los-db',
    authDomain: 'los-db.firebaseapp.com',
    storageBucket: 'los-db.appspot.com',
    measurementId: 'G-Y3P39KS97W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc0aFez26GVJTxBsQcsSFhqblilRobTlo',
    appId: '1:550489230441:android:485fc6de1d4140774626f8',
    messagingSenderId: '550489230441',
    projectId: 'los-db',
    storageBucket: 'los-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBujwfohYfIxXVXSfUITOpZ0NsqC6XJVVs',
    appId: '1:550489230441:ios:ec0073baf8545a9c4626f8',
    messagingSenderId: '550489230441',
    projectId: 'los-db',
    storageBucket: 'los-db.appspot.com',
    iosClientId: '550489230441-nausnhgsg4s2hsc7msj8ijm59fsevoul.apps.googleusercontent.com',
    iosBundleId: 'com.example.losApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBujwfohYfIxXVXSfUITOpZ0NsqC6XJVVs',
    appId: '1:550489230441:ios:6b0d440686d921ff4626f8',
    messagingSenderId: '550489230441',
    projectId: 'los-db',
    storageBucket: 'los-db.appspot.com',
    iosClientId: '550489230441-bgm3cn36kmj2qi7gns9rphdumd1e7qak.apps.googleusercontent.com',
    iosBundleId: 'com.example.losApp.RunnerTests',
  );
}
